config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  get  '/alumni' => 'static_pages#alumni'
  get  '/brothers' => 'static_pages#brothers'
  get  '/chapter'=> 'static_pages#chapter'
  get  '/signup',  to: 'users#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def alumni
  end

  def brothers
  end

  def chapter
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "FIJI Tau Kappa"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.phigam.org/">Internaitonal Fraternity</a>
    of <a href="http://fijitk.com/">Phi Gamma Delta - Tau Kappa Chapter</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <%= image_tag("fiji_logo.png", alt: "FIJI Tau Kappa", size:"25")%>
        </a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home",    "/" %></li>
          <li><%= link_to "Chapter",    chapter_path %></li>
          <li><%= link_to "Brothers",   brothers_path %></li>
          <li><%= link_to "Alumni",   alumni_path %></li>
          <li><%= link_to "Login",    root_path%></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/alumni.html.erb
<% provide(:title, "Alumni") %>
<h1>Alumni</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/brothers.html.erb
<% provide(:title, "Brothers") %>
<h1 class="my-4">About Us
        <small>It's Nice to Meet You!</small>
      </h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint, explicabo dolores ipsam aliquam inventore corrupti eveniet quisquam quod totam laudantium repudiandae obcaecati ea consectetur debitis velit facere nisi expedita vel?</p>

      <!-- Team Members Row -->
      <div class="row">
        <div class="col-lg-12">
          <h2 class="my-4">Our Team</h2>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>John Smith
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>John Smith
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>John Smith
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>John Smith
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>John Smith
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
        <div class="col-lg-4 col-sm-6 text-center mb-4">
          <img class="rounded-circle img-fluid d-block mx-auto" src="http://placehold.it/200x200" alt="">
          <h3>John Smith
            <small>Job Title</small>
          </h3>
          <p>What does this team member to? Keep it short! This is also a great spot for social links!</p>
        </div>
      </div>

    </div>

app/views/static_pages/chapter.html.erb
<% provide(:title, "Chapter") %>
<h1>Chapter</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


<div class="parallax center">
  <%= image_tag("fiji_crest.png", width: "10%")%>
  <h1>Phi Gamma Delta</h1>
	<p>Tau Kappa Chapter</p>
  <p>University of Toronto</p>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<div class="container">
	<div class="row white">
      <br>
      <h1 class="centered">ABOUT OUR BROTHERHOOD</h1>
      <hr>
      
      <div class="col-lg-6">
        <p>We believe ideas come from everyone, everywhere. In fact, at BlackTie, everyone within our agency walls is a designer in their own right. 
        And there are a few principles we believe—and we believe everyone should believe—about our design craft. These truths drive us, motivate us, 
        and ultimately help us redefine the power of design. We’re big believers in doing right by our neighbors. After all, we grew up in the Twin 
        Cities and we believe this place has much to offer. So we do what we can to support the community we.</p>
      </div><!-- col-lg-6 -->
      
      <div class="col-lg-6">
      <%= image_tag("pig.png", alt: "Chapter", width: "99%")%>
      </div><!-- col-lg-6 -->
	</div><!-- row -->
</div><!-- container -->


<div class="wrapper purple center">
  <div class="fullwidth row">
    <img height="71" src="https://www.phigam.org/image/Icon-Cabin1.png" width="72" /><br /><br />

    <h4>FOUNDING</h4>
    <p>May 1, 1848 at Jefferson College in Canonsburg, PA<br /><br />

    <img height="16" src="https://www.phigam.org/image/Icon-Values.png" width="100" /></p>
    <h4>OUR VALUES</h4>
    <p>Friendship, Knowledge, Service, Morality, Excellence<br /><br />

    <img height="47" src="https://www.phigam.org/image/icon-mission.png" width="81" /></p>
    <h4>OUR MISSION</h4>
    <p>Phi Gamma Delta unites men in enduring friendships, stimulates the pursuit of knowledge, and builds courageous leaders who serve the world with the best that is in them.<br /><br />
    
    <img height="68" src="https://www.phigam.org/image/Icon-Numbers1.png" width="49" /></p>
    <h4>BY THE NUMBERS</h4>
    <p><span style="text-decoration: underline;">180,000+</span> initiated brothers since 1848<br /> 
    <span style="text-decoration: underline;">11,000+</span> undergraduate brothers in <span style="text-decoration: underline;">153</span>&#160;Chapters and <span style="text-decoration: underline;">13</span>&#160;Colonies</p>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>